// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using auth_service.src.Auth.Infrastructure.Persistence;

#nullable disable

namespace Auth.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("auth_service.src.Auth.Domain.Entities.AuthAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEmailVerified");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId");

                    b.ToTable("Auth_Accounts", "dbo");
                });

            modelBuilder.Entity("auth_service.src.Auth.Domain.Entities.AuthRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Auth_Roles", "dbo");
                });

            modelBuilder.Entity("auth_service.src.Auth.Domain.Entities.AuthUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("AssignedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "UserId");

                    b.ToTable("Auth_UserRoles", "dbo");
                });

            modelBuilder.Entity("auth_service.src.Auth.Domain.Entities.LoginAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FailureReason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("IpAddress");

                    b.Property<bool>("Success")
                        .HasColumnType("bit")
                        .HasColumnName("Success");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserAgent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Auth_LoginAuditLogs", "dbo");
                });

            modelBuilder.Entity("auth_service.src.Auth.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TokenId");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DeviceId");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ExpiresAt");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("IpAddress");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("IssuedAt");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReplacedByTokenId");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("RevokedAt");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("TokenHash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserAgent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("Auth_RefreshTokens", "dbo");
                });

            modelBuilder.Entity("auth_service.src.Auth.Infrastructure.Persistence.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AggregateId");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EventType");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("OccurredAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ProcessedAt");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TraceId");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("Auth_OutboxEvents", "dbo");
                });

            modelBuilder.Entity("auth_service.src.Auth.Domain.Entities.AuthAccount", b =>
                {
                    b.OwnsOne("auth_service.src.Auth.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AuthAccountUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("AuthAccountUserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("UX_Auth_Accounts_Email");

                            b1.ToTable("Auth_Accounts", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("AuthAccountUserId");
                        });

                    b.OwnsOne("auth_service.src.Auth.Domain.ValueObjects.PasswordHash", "Password", b1 =>
                        {
                            b1.Property<Guid>("AuthAccountUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PasswordAlgo");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("varbinary(256)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("AuthAccountUserId");

                            b1.ToTable("Auth_Accounts", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("AuthAccountUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
