version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: notification-mongo
    ports:
      - "27019:27017"
    volumes:
      - notification_mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    ports:
      - "5677:5672"
      - "15677:15672"

  mailhog:
    image: mailhog/mailhog
    container_name: notification-mailhog
    ports:
      - "1026:1025"
      - "8026:8025"

  notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-api
    depends_on:
      - mongo
      - rabbitmq
      - mailhog
    environment:
      NODE_ENV: development
      PORT: 5010
      MONGO_URI: mongodb://mongo:27017/notification_service
      RABBIT_URL: amqp://rabbitmq:5672
      RABBIT_EXCHANGE: events
      SERVICE_NAME: notification-service
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASS: ""
      MAIL_FROM: noreply@tdmu.local
      USER_SERVICE_URL: http://host.docker.internal:5002
      WS_ENABLED: "true"
      PUSH_ENABLED: "false"
    ports:
      - "5010:5010"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  notification_mongo_data: